name: AutoModpackPlugin
version: "@pluginVersion@"
description: Bridge plugin to integrate AutoModpack with Paper/Spigot servers.
authors:
  - AutoModpack Team
website: https://modrinth.com/mod/automodpack
main: com.cufufy.amp.plugin.AutoModpackPlugin
api-version: "1.20"
