name: AutoModpackPlugin
main: pl.skidam.automodpack.plugin.AutoModpackPlugin
version: "@pluginVersion@"
api-version: "1.20"
author: AutoModpack Team
description: Bridge plugin to integrate AutoModpack with Paper/Spigot servers.
website: https://modrinth.com/mod/automodpack
depend: []
softdepend: []
load: STARTUP
commands:
  automodpack:
    description: Controls AutoModpack hosting and configuration.
    usage: /automodpack [generate|host|config]
    aliases: [amp]
    permission: automodpack.admin
permissions:
  automodpack.admin:
    description: Allows access to AutoModpack administrative commands.
    default: op
