name: AutoModpackPlugin
main: pl.skidam.automodpack.plugin.AutoModpackPlugin
version: 1.0.0
api-version: "1.20"
author: AutoModpack Team
description: Bridge plugin to integrate AutoModpack with Paper/Spigot servers.
website: https://modrinth.com/mod/automodpack
depend: []
softdepend: []
load: STARTUP
